spring.application.name=backend
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.defer-datasource-initialization=true
spring.data.jdbc.dialect=mysql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.servlet.encoding.charset=UTF-8
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server.error.include-stacktrace=on_param
server.port=8080

host=intproj24.sit.kmutt.ac.th/ssi4